version: '3'

services:

  db:
    image: containerregistryionuttamas30241.azurecr.io/db
    
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Admin123!" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    restart: always
    environment:
      SA_PASSWORD: "Admin123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  be:
    image: containerregistryionuttamas30241.azurecr.io/tamasionut30241backend:21
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy

  rabbitmq-deploy:
    image: rabbitmq:3.11-management
    ports:
        - 5672:5672
        - 15672:15672